# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ai-window/form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QCoreApplication
from db_module import write_to_db
from PyQt5.QtGui import QFont




class Ui_MainWindow(object):
    def setupUi(self, MainWindow, datalist):
        MainWindow.setObjectName("Llama Answer")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setBaseSize(QtCore.QSize(800, 600))
        MainWindow.setDocumentMode(True)
        MainWindow.setWindowIcon(QtGui.QIcon('data/punk_icon.png'))
        # set the title
        # self.setWindowTitle("Llama Answer")
 
        self.datalist = datalist
        self.question = datalist[1]
        self.answer = datalist[2]
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 480, 181, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(520, 480, 181, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 30, 691, 351))
        self.label.setText('Q: ' + self.question + '\n\n' + 'A: ' + self.answer)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label.setFont(QFont('Ubuntu', 15))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.write_to_base(self.datalist)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Llama Answer", "Llama Answer"))
        self.pushButton.setText(_translate("MainWindow", "Write in DB"))
        self.pushButton_2.setText(_translate("MainWindow", "Exit"))

    def write_to_base(self, datalist):
        print(self.datalist)
        self.pushButton.clicked.connect(lambda: write_and_close(self.datalist))
        self.pushButton_2.clicked.connect(QCoreApplication.instance().quit)

def write_and_close(datalist):
    write_to_db(data_list=datalist)
    print("Quit")
    QCoreApplication.instance().quit()

def start_window(data_text_list):
    # print(data_text_list)
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow, datalist=data_text_list)
    multiplier_x = 1
    multiplier_y = 2
    cursor_pos = QtWidgets.QApplication.desktop().cursor().pos()
    screen = QtWidgets.QApplication.desktop().screenNumber(cursor_pos)
    pos_x = QtWidgets.QDesktopWidget().screenGeometry(screen).center().x()
    pos_x -= MainWindow.frameGeometry().center().x() * multiplier_x
    pos_y = QtWidgets.QDesktopWidget().screenGeometry(screen).center().y()
    pos_y -= MainWindow.frameGeometry().center().y() * multiplier_y
    MainWindow.move(pos_x, pos_y)
    MainWindow.show()
    sys.exit(app.exec_())
