# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'temp_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QTimer
from PyQt5.QtCore import QCoreApplication

import time
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, label_text):
        self.label_text = label_text
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 200)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 461, 121))
        self.label.setText(self.label_text)
        self.label.setObjectName("label")
        self.label.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        # self.close()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.timer = QTimer(MainWindow)
        self.timer.setSingleShot(True)
        self.timer.timeout.connect(MainWindow.close)
        self.timer.start(5000)  # 5000 ms = 5 seconds

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Question"))

        
def temp_window_start(label_text):
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow, label_text)
    MainWindow.show()
    
    # Start the main event loop
    app.exec_()
